### ISSUE TITLE
Filter by assemblies length

### ISSUE THREAD

**Issue by davidtong28** [cidgoh/bacpaq#11]
### Description of feature

Add a skippable step in post assembly QC to filter out unwanted assembly length. The length may come from the Quast report. This is most useful in WGS of a known species. Parameters should include:

- [ ] Add skip_length_filter=True
- [ ] Add param for min_length
- [ ] (Optional) add max_length
- [ ] Install seqkit_seq module from nf-core
- [ ] Integrate into a subworkflow

**Comment by azmigueldario** [comment]
Created a new process to filter by length 
 - optional process
 - params define if its run and what are the min/max thresholds

Tested with nanopore/illumina fastq reads
