### ISSUE TITLE
MultiQC format needs improvement

### ISSUE THREAD

**Issue by anwarMZ** [cidgoh/bacpaq#63]
### Description of the bug

- If there are two FastQC sections displaying the read stats before/after preprocessing, then why are there six samples in each FastQC diagram? I'm expecting 3 samples, as the nanopore data is not analyzed by FastQC.

- The general statistics table has too many missing values making it hard to understand. Likely need to split it into multiple tables

**Comment by jimmyliu1326** [comment]
> If there are two FastQC sections displaying the read stats before/after preprocessing, then why are there six samples in each FastQC diagram? I'm expecting 3 samples, as the nanopore data is not analyzed by FastQC.

Just realized the reason is because those correspond to forward and reverse reads..
