### ISSUE TITLE
Create a nextflow module for medaka_variant

### ISSUE THREAD

**Issue by jimmyliu1326** [cidgoh/bacpaq#81]
### Description of feature

`medaka_variant` is not available through nf-core. Write a nf-core standard [medaka_variant](https://github.com/nanoporetech/medaka) module

- [ ] include a Singularity/docker container
- [ ] include a bioconda container

**Comment by azmigueldario** [comment]
created local module for medaka variant, tested with toy dataset of long reads. Output includes several `.vcf`, and a `.bam`/`.bam.bai` pair per input

Old versions of medaka do not accept reads for variant calling, so the image was bumped to v2.0.1
