### ISSUE TITLE
Create a Nextflow module for delta2vcf

### ISSUE THREAD

**Issue by jimmyliu1326** [cidgoh/bacpaq#83]
### Description of feature

delta2vcf is not available through nf-core. Write a nf-core standard [delta2vcf](https://github.com/mummer4/mummer/blob/master/scripts/delta2vcf.pl) module

- [ ] include a Singularity/docker container
- [ ] include a bioconda container

**Comment by azmigueldario** [comment]
`delta2vcf.pl` is added to `./bin` and is executed after calling perl in the process
Tested with a toy dataset.
Will be implemented in branch of variant calling subworkflow
